const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');

async function sendEmailNotification(newSongs, baseHtmlPath, searchName) {
    if (process.env.DRY_RUN === 'true') {
        console.log(`[DRY RUN] Skipping email notification for ${searchName}`);
        return;
    }
    // Load secrets
    const secretsPath = path.resolve(__dirname, '../../configs/secrets.json');
    if (!fs.existsSync(secretsPath)) {
        console.error(`ERROR: Secrets file not found at ${secretsPath}. Cannot send email.`);
        return;
    }

    const secrets = JSON.parse(fs.readFileSync(secretsPath, 'utf8'));
    if (!secrets.gmailUser || !secrets.gmailAppPassword) {
        console.error("ERROR: Invalid secrets.json. Missing gmailUser or gmailAppPassword.");
        return;
    }

    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: secrets.gmailUser,
            pass: secrets.gmailAppPassword
        }
    });

    let htmlContent;
    let subject;

    if (!newSongs || newSongs.length === 0) {
        subject = `[Music Release Alert - ${searchName}] Search Run Completed - No New Songs`;
        htmlContent = `
            <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 640px; margin: 0 auto; color: #1e293b; padding: 20px;">
                <h2 style="color: #0f172a; margin-top: 0;">Live Music Search Agent</h2>
                <p style="color: #64748b;">A scheduled run was completed, but no new songs were discovered on <strong>${searchName}</strong> today.</p>
            </div>
        `;
    } else {
        subject = `[Music Release Alert - ${searchName}] ${newSongs.length} New Indie/Live Songs Discovered!`;
        htmlContent = `
            <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 640px; margin: 0 auto; color: #1e293b; line-height: 1.5; padding: 20px;">
                <div style="border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-bottom: 20px;">
                    <h2 style="color: #0f172a; margin: 0 0 6px 0;">New Music Releases Discovered</h2>
                    <p style="color: #64748b; margin: 0; font-size: 0.95rem;">
                        <strong>${searchName}</strong> found <strong>${newSongs.length}</strong> new song${newSongs.length === 1 ? '' : 's'}.
                    </p>
                </div>

                <div style="background-color: #f0f9ff; border: 1px solid #bae6fd; border-radius: 8px; padding: 12px 16px; margin-bottom: 24px; font-size: 0.88rem; color: #0369a1;">
                    💡 <strong>Sanity Tip:</strong> For songs you choose to publish, select the <em>Discovery Source</em> and copy the <em>Source URL</em> below directly into Sanity.
                </div>

                <div>
                    ${newSongs.map(song => `
                        <div style="background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
                            <div style="font-size: 1.1rem; font-weight: 700; color: #0f172a; margin-bottom: 8px;">
                                ${song.title}
                            </div>
                            <div style="font-size: 0.88rem; color: #475569; margin-bottom: 6px;">
                                <strong style="color: #334155;">Source:</strong> 
                                <span style="background-color: #e2e8f0; color: #0f172a; padding: 2px 8px; border-radius: 4px; font-weight: 600;">${song.channel || searchName}</span>
                                ${song.uploadedAt ? `<span style="color: #94a3b8; margin-left: 8px;">(${song.uploadedAt})</span>` : ''}
                            </div>
                            <div style="font-size: 0.88rem; color: #475569; margin-bottom: 8px; word-break: break-all;">
                                <strong style="color: #334155;">Source URL:</strong> 
                                <a href="${song.url}" target="_blank" style="color: #0284c7; text-decoration: underline;">${song.url}</a>
                            </div>
                            ${song.description ? `
                                <div style="font-size: 0.82rem; color: #64748b; background-color: #f8fafc; padding: 6px 10px; border-radius: 4px; margin-top: 6px;">
                                    ${song.description}
                                </div>
                            ` : ''}
                        </div>
                    `).join('')}
                </div>
                
                <p style="color: #94a3b8; font-size: 0.85rem; margin-top: 30px; text-align: center;">
                    Generated by Live Music Search Agent &bull; New Indie Friday Discovery Pipeline
                </p>
            </div>
        `;
    }

    const mailOptions = {
        from: secrets.gmailUser,
        to: secrets.gmailUser,
        subject: subject,
        html: htmlContent
    };

    if (baseHtmlPath) {
        mailOptions.html += `
            <hr style="margin-top: 20px; border: none; border-top: 1px solid #ccc;">
            <p style="font-size: 0.9em; color: #555;">
                <a href="file://${baseHtmlPath.replace(/\\/g, '/')}">View Original Base Run</a>
            </p>
        `;
    }

    try {
        console.log("Sending email notification...");
        const info = await transporter.sendMail(mailOptions);
        console.log("Email sent successfully: " + info.response);
    } catch (error) {
        console.error("Error sending email:", error);
    }
}

async function sendReminderEmail(subject, htmlContent) {
    if (process.env.DRY_RUN === 'true') {
        console.log(`[DRY RUN] Skipping reminder email: ${subject}`);
        return;
    }
    const secretsPath = path.resolve(__dirname, '../../configs/secrets.json');
    if (!fs.existsSync(secretsPath)) {
        console.error(`ERROR: Secrets file not found at ${secretsPath}. Cannot send email.`);
        return;
    }

    const secrets = JSON.parse(fs.readFileSync(secretsPath, 'utf8'));
    if (!secrets.gmailUser || !secrets.gmailAppPassword) {
        console.error("ERROR: Invalid secrets.json. Missing gmailUser or gmailAppPassword.");
        return;
    }

    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: secrets.gmailUser,
            pass: secrets.gmailAppPassword
        }
    });

    const mailOptions = {
        from: secrets.gmailUser,
        to: secrets.gmailUser,
        subject: subject,
        html: htmlContent
    };

    try {
        console.log(`Sending reminder email: ${subject}...`);
        const info = await transporter.sendMail(mailOptions);
        console.log("Reminder email sent successfully: " + info.response);
    } catch (error) {
        console.error("Error sending reminder email:", error);
    }
}

module.exports = {
    sendEmailNotification,
    sendReminderEmail
};
